### ISSUE TITLE
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: 

### ISSUE THREAD

**Issue by chlung** [Tedezed/kubernetes-containers-tools#2]
Hi,

I am getting the following error.  Any suggestion about how to fix it.

ver 0.0.0.5
Start Slug StatefulSet Autoscaler v.0.0.1
Traceback (most recent call last):
  File "/slug_statefulset_autoscaler/main.py", line 57, in <module>
    list_set = select_statefulset(api, namespace)
  File "/slug_statefulset_autoscaler/tools.py", line 39, in select_statefulset
    for s in pre_set.response['items']:
  File "/usr/local/lib/python2.7/dist-packages/pykube/query.py", line 137, in response
    return self.query_cache["response"]
  File "/usr/local/lib/python2.7/dist-packages/pykube/query.py", line 123, in query_cache
    cache["response"] = self.execute().json()
  File "/usr/local/lib/python2.7/dist-packages/pykube/query.py", line 108, in execute
    r.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://kubernetes:443/apis/apps/v1beta1/namespaces/default/statefulsets

Thanks.

**Comment by Tedezed** [comment]
Hi! Did you create the service account? If you created it, maybe it is that you need more permissions. How did you execute it?

**Comment by chlung** [comment]
I haven't created any service account.  Do I need to create one.  I am following http://www.aventurabinaria.es/kubernetes-stateful-set-autoscale/. 
Thanks.

**Comment by Tedezed** [comment]
You can use this example, this is more complete: https://github.com/Tedezed/slug-containers/tree/master/statefulset_autoscaler/kube

Service account: https://github.com/Tedezed/slug-containers/blob/master/statefulset_autoscaler/kube/slug-autoscaler-rc.yaml#L1-L5

Changes: https://github.com/Tedezed/slug-containers/issues/1

**Comment by chlung** [comment]
Thanks a lot.
